---
# タイムゾーンの変更
- name: change timezone
  raw: cp -f /usr/share/zoneinfo/Japan /etc/localtime
# システム言語の変更
- name: change system language
  lineinfile: dest=/etc/sysconfig/i18n regexp="^LANG=\"en_US\.UTF-8\"" line="LANG=\"ja_JP.UTF-8\"" backrefs=yes
# sshdの設定変更
- name: change sshd_config 1
  lineinfile: dest=/etc/ssh/sshd_config regexp="^\s*UseDNS\s" line="UseDNS no"
- name: change sshd_config 2
  lineinfile: dest=/etc/ssh/sshd_config regexp="^\s*GSSAPIAuthentication\s" line="GSSAPIAuthentication no"
- name: change sshd_config 3
  lineinfile: dest=/etc/ssh/sshd_config regexp="^\s*AddressFamily\s" line="AddressFamily inet"
- name: restart sshd
  service: name=sshd state=restarted
# userを追加
- name: useradd main_username
  user: name={{ l_main_username }} password={{ l_main_password }}
# パッケージを更新
- name: yum update
  command: yum -y update
# 不要なサービスの停止と自動起動をオフに
- name: stop services
  service: name={{ item }} state=stopped
  with_items:
    - sendmail
- name: disable services
  service: name={{ item }} enabled=no
  with_items:
    - mdmonitor
    - sendmail
    - netfs
# 色々パッケージを追加
- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - subversion
