---
# cloud-initの設定
- name: change cloud.cfg 1
  lineinfile: dest=/etc/cloud/cloud.cfg regexp="^repo_upgrade:.*" line="repo_upgrade{{colon}} none"
- name: change cloud.cfg 2
  lineinfile: dest=/etc/cloud/cloud.cfg regexp="^locale:.*" line="locale{{colon}} ja_JP.UTF-8"
# タイムゾーンの変更
- name: change timezone 1
  raw: cp -f /usr/share/zoneinfo/Japan /etc/localtime
- name: change timezone 2
  lineinfile: dest=/etc/sysconfig/clock regexp="^ZONE=.*" line="ZONE=\"Asia/Tokyo\""
- name: change timezone 3
  lineinfile: dest=/etc/sysconfig/clock regexp="^UTC=.*" line="UTC=False"
- name: change timezone 4
  lineinfile: dest=/etc/sysconfig/clock regexp="^ARC=.*" line="ARC=False"
# システム言語の変更
- name: change system language
  lineinfile: dest=/etc/sysconfig/i18n regexp="^LANG=\"en_US\.UTF-8\"" line="LANG=\"ja_JP.UTF-8\"" backrefs=yes
# sshdの設定変更
- name: change sshd_config 1
  lineinfile: dest=/etc/ssh/sshd_config regexp="^\s*UseDNS\s" line="UseDNS no"
- name: change sshd_config 2
  lineinfile: dest=/etc/ssh/sshd_config regexp="^\s*GSSAPIAuthentication\s" line="GSSAPIAuthentication no"
- name: change sshd_config 3
  lineinfile: dest=/etc/ssh/sshd_config regexp="^\s*AddressFamily\s" line="AddressFamily inet"
- name: restart sshd
  service: name=sshd state=restarted
# userを追加
- name: useradd main_username
  user: name={{ l_main_username }} password={{ l_main_password }}
# パッケージを更新
- name: yum update
  command: yum -y update
# 不要なサービスの停止と自動起動をオフに
- name: stop services
  service: name={{ item }} state=stopped
  with_items:
    - sendmail
- name: disable services
  service: name={{ item }} enabled=no
  with_items:
    - mdmonitor
    - sendmail
    - netfs
# 色々パッケージを追加
- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - subversion
